# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2d856a555151d0c1bf1167c224746cde759d9d92273a22c6ef19050ea9b2cfbb6bf11b06934784d2340bfedb1e7f42a3df6317dd4993dfea26549e2af67fc8cf

test:
  secret_key_base: 6112382b7db69c4ea88518ca4a67acb082cc44e7a9cba6550f26668fe3646469c72c77c688121d01b1163b8a2560c7ba2b5b708e52ca8963b3eaf52b1246d061

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
